name: BuildLinuxFFMPEGLibs

on:
  push:
    branches:
    # Change this to the branch name which you are developing on to trigger the workflow
    - main

jobs:
  GenerateLinuxStaticLibraries:
    runs-on: ubuntu-20.04

    steps:
    - name: Download and Build Freetype2
      run: |
        # Clone freetype2 repo
        git clone --depth 1 https://git.savannah.nongnu.org/git/freetype/freetype2.git
        cd freetype2
        ./autogen.sh
        mkdir build
        cd build
        ../configure \
          --disable-shared \
          --enable-static \
          --with-png=no \
          --with-harfbuzz=no \
          --with-bzip2=no \
          --with-zlib=no
        
        make -j4
        sudo make install
    - name: Download and Build FFMPEG 5
      run: |
        # Install required packages 
        sudo apt-get install nasm
        
        # Clone FFMPEG repo
        git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git -b release/5.0
        # Create shadow build folder
        mkdir build
        mkdir installed
        cd ./build/ 
        # Configure project
        #export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/d/a/freetype/:/d/a/freetype/lib:/d/a/freetype/lib/pkgconfig
        ../ffmpeg/configure --help
        
        ../ffmpeg/configure \
             --prefix=../installed \
             --pkg-config-flags="--static" \
             --extra-libs="-lpthread -lm" \
             --ld="g++" \
             --enable-static \
             --disable-shared \
             --enable-yasm  \
             --enable-asm \
             --disable-doc \
             --disable-programs \
             --disable-large-tests \
             --disable-indevs \
             --disable-bzlib \
             --disable-iconv \
             --disable-libxcb \
             --disable-zlib \
             --enable-gpl \
             --enable-nonfree \
             --enable-libfreetype \
             --enable-filter=drawtext  
             
         # Build FFMPEG
         make -j 8
         make install
    - name: Package binaries
      run: |
        # Create archive of the pre-built FFMPEG libraries
        7z a ffmpeg-libs-linux-static.zip .\installed
    - uses: actions/upload-artifact@v1
      with:
        name: ffmpeg-libs-linux-static.zip
        path: ffmpeg-libs-linux-static.zip
