name: BuildFFMPEGLibs

on:
  push:
    branches:
    # Change this to the branch name which you are developing on to trigger the workflow
    - main

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2019

    steps:
    - name: Download freetype
      run: |
        # Download the pre-built static version of freetype2
        #Invoke-WebRequest https://dl.xirac.com/qt/freetype-lib.zip -OutFile .\freetype-lib.zip
        #expand-archive -path "freetype-lib.zip" -destinationpath "d:/freetype"
        #dir d:/freetype/  
        ##echo "d:\freetype\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Clone repository
      uses: actions/checkout@v2
#     - name: Set up msvc
#       uses: ilammy/msvc-dev-cmd@v1
    - name: Set up msys
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          autoconf
          automake
          libtool 
          m4
          diffutils 
          yasm 
          nasm
          git
          mingw-w64-x86_64-toolchain
        path-type: inherit
    - name: Build project
      run: |
        #make
        #mingw-w64-x86_64-gcc
      
        #mv /usr/bin/link.exe /usr/bin/link.exe.bak 
        
        git clone --depth 1 https://git.savannah.nongnu.org/git/freetype/freetype2.git
        
        cd freetype2
        ./autogen.sh
        ./configure --help
        ./configure --prefix=/d/a/freetype/ --disable-shared --enable-static --build=windows --target=mingw32 --with-png=no --with-harfbuzz=no --with-bzip2=no
        make -j4
        make install
        #mingw32-make -j4
        #mingw32-make install
        
        cd ..        
         
        # Clone FFMPEG repo
        git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git -b release/5.0
        # Create shadow build folder
        mkdir build
        mkdir installed
        cd ./build/ 
        # Configure and build project
        #export CC=cl 
        pwd
        ls -l ../../../freetype/
        ls -l ../../../freetype/lib
        ls -l ../../../freetype/lib/pkgconfig
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/d/a/freetype/:/d/a/freetype/lib:/d/a/freetype/lib/pkgconfig
        
        echo $PKG_CONFIG_PATH
        ../ffmpeg/configure --help
        
        #--toolchain=msvc \
        
        ../ffmpeg/configure \
             --prefix=../installed \
             --target-os=win64 \
             --arch=x86_64 \
             --enable-yasm  \
             --enable-asm \
             --disable-doc \
             --disable-programs \
             --enable-gpl \
             --enable-nonfree \
             --enable-libfreetype \
             --enable-filter=drawtext \
             --extra-ldflags="-LIBPATH:../../../freetype/lib/" \
             --extra-cflags="-I../../../freetype/include/"  
         #make V=1 -j 8
         mingw32-make V=1 -j8
         #make install
         mingw32-make install
      shell: msys2 {0}
    - name: Package binaries
      run: |
        # Create archive of the pre-built FFMPEG libraries
        7z a ffmpeg-libs.zip .\installed
    - uses: actions/upload-artifact@v1
      with:
        name: ffmpeg-libs.zip
        path: ffmpeg-libs.zip
