name: BuildFFMPEGLibs

on:
  push:
    branches:
    # Change this to the branch name which you are developing on to trigger the workflow
    - main

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2019

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up msvc
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set up msys
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make 
          diffutils 
          yasm 
          nasm
          git
        path-type: inherit
    - name: Build project
      run: |
        mv /usr/bin/link.exe /usr/bin/link.exe.bak 
        # Clone FFMPEG repo
        git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git -b release/5.0
        # Create shadow build folder
        mkdir build
        mkdir installed
        cd ./build/ 
        # Configure and build project
        export CC=cl 
        ../ffmpeg/configure \
             --prefix=../installed \
             --target-os=win64 \
             --toolchain=msvc \
             --arch=x86_64 \
             --enable-yasm  \
             --enable-asm \
             --disable-doc \
             --disable-programs \
             --enable-gpl \
             --enable-nonfree \
             --enable-libfreetype \
             --extra-ldflags="-LIBPATH:../installed/lib/" \
             --extra-cflags="-I../installed/include/" 
         make V=1 -j 8 
         make install
      shell: msys2 {0}
    - name: Package binaries
      run: |
        # Create archive of the pre-built FFMPEG libraries
        7z a ffmpeg-libs.zip .\installed
    - uses: actions/upload-artifact@v1
      with:
        name: ffmpeg-libs.zip
        path: ffmpeg-libs.zip
