name: BuildWindowsFFMPEGLibs

on:
  push:
    branches:
    # Change this to the branch name which you are developing on to trigger the workflow
    - main

jobs:
  GenerateWinStaticLibraries:
    runs-on: windows-2019

    steps:
      # To use MSVC you should use this plugin
#     - name: Set up msvc
#       uses: ilammy/msvc-dev-cmd@v1
    - name: Set up msys
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          autoconf
          automake
          libtool 
          m4
          diffutils 
          yasm 
          nasm
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-freetype
        path-type: inherit
    - name: Build project
      run: |
        # Clone FFMPEG repo
        git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git -b release/5.0
        # Create shadow build folder
        mkdir build
        mkdir installed
        cd ./build/ 
        # Configure and build project
        ../ffmpeg/configure --help
        
        ../ffmpeg/configure \
             --prefix=../installed \
             --target-os=win64 \
             --arch=x86_64 \
             --enable-static \
             --disable-static \
             --enable-yasm  \
             --enable-asm \
             --disable-doc \
             --disable-programs \
             --disable-large-tests \
             --disable-indevs \
             --disable-bzlib \
             --disable-iconv \
             --disable-libxcb \
             --disable-zlib \
             --enable-gpl \
             --enable-nonfree \
             --enable-libfreetype \
             --enable-filter=drawtext
         
         make -j8
         make install
      shell: msys2 {0}
    - name: Package binaries
      run: |
        # Create archive of the pre-built FFMPEG libraries
        7z a ffmpeg-libs-win64-static.7z .\installed
    - uses: actions/upload-artifact@v1
      with:
        name: ffmpeg-libs-win64-static.zip
        path: ffmpeg-libs-win64-static.7z
